### ISSUE TITLE
Possibility to migrate to voxpupuli

### ISSUE THREAD

**Issue by tuxmea** [djjudas21/puppet-freeradius#131]
@jgazeleyfr in https://github.com/djjudas21/puppet-freeradius/issues/129#issuecomment-547357272_ you mentioned that you are not able to continue working on this module.
Do you see the possibility to migrate the module to voxpupuli so we can collaboratively continue working on this module?

https://voxpupuli.org/docs/migrate_module/

**Comment by jgazeleyfr** [comment]
Hi, sorry I took so long to respond. I have considered Voxpupuli but at the moment I am satisfied that quite a few people are still developing and submitting PRs, so developing is continuing, albeit slowly.

I am currently considering changing job in January into a role where I am once again working with Puppet and FreeRADIUS, so at that point I'll be able to continue development myself.

**Comment by djjudas21** [comment]
I have now contacted the Vox Pupuli mailing list to start this process.

**Comment by jnk0** [comment]
Are you still in contact with the Vox Pupuli team? I wonder if the plan to migrate to the project is still being pursued.

**Comment by djjudas21** [comment]
Hi @jnk0 I actually didn't get any response from the Vox Pupuli team, but I didn't chase it up because it looked like I managed to recruit a few maintainers on this project that could keep it going in #147.

I admit progress has been slow and I apologise for this. I'll talk to my collaborators and we can review whether it's worth trying to migrate to Vox Pupuli again, or whether I can get some more maintainers here. I'm not precious about the project and I'm happy to add people to the repo as maintainers if they have something to contribute :slightly_smiling_face:

**Comment by djjudas21** [comment]
Given that we've managed to do significant maintenance work on this project by appointing a couple of new collaborators (thanks @nward and @amateo) and receiving PRs from various members of the community, I'm going to close this for now.

We're always happy to receive contributions in the form of issues and PRs, and if anyone thinks they can spare some time to work on refactoring and improvements, just drop a comment and I can add you as a collaborator. Thanks.
