### ISSUE TITLE
Puppetlabs/firewall module dependency

### ISSUE THREAD

**Issue by deligatedgeek** [djjudas21/puppet-freeradius#168]
Currently this module has a dependency on an old version of Puppetlabs/firewall, are there any plans to update this dependency?

I am happy submit a PR for a newer version

**Comment by djjudas21** [comment]
Hi there. I must admit, this wasn't on our radar but I think it's a good idea. If you could submit a PR for this that would be great, thanks.

**Comment by djjudas21** [comment]
Against main, please. Should be nice and easy to merge 🙂

**Comment by deligatedgeek** [comment]
https://github.com/djjudas21/puppet-freeradius/pull/170 ready for review 8-)

**Comment by deligatedgeek** [comment]
Thanks Jonathan.  Once we are running with a higher version of puppetlabs firewall module and can test, I'll create another PR

**Comment by djjudas21** [comment]
Thanks @deligatedgeek, that's great. I've also restarted discussed with my collaborators about doing another release, because I've just realised it's been over 2 years now! There's a lot of improvements that have never been tagged in a release. Feel free to weigh in on #156 if you have any strong feelings about that :smile:

**Comment by deligatedgeek** [comment]
Excellent, will check https://github.com/djjudas21/puppet-freeradius/issues/156 out.
