### ISSUE TITLE
sites directly in sites-enabled

### ISSUE THREAD

**Issue by thtomate** [djjudas21/puppet-freeradius#83]
I already knew that sites were added to sites-enabled directly and didn't care, but yesterday I discovered that this caused serious problem at least with Debian package management: It creates a symlink "default" in sites-enabled, which overrides a site named "default" created with this module by puppet. This is when the downtime starts.
A puppet run would not fix it, because puppet does not care of content if it is a symlink.
This is where the downtime gets permanent until you delete the symlink and run puppet again.

The freeradius devs advise/instruct to use links in sites-enabled:
```
#	Virtual hosts should be put into the "sites-available"
#	directory.  Soft links should be created in the "sites-enabled"
#	directory to these files.
```

From my point of view it would be better to create the file in sites-available and a symlink to it in sites-enabled, just as "anyone else". Are there any arguments for keeping the old behaviour?

A workaround is renaming the sites to unused names.

**Comment by djjudas21** [comment]
This module is designed so it takes total control of everything in `/etc/freeradius` and the user shouldn't need to touch anything, so in that sense it doesn't matter whether the module puts data in `sites-enabled` or `sites-available` and creates symlinks.

This module does not create a site named `default` unless you tell it to, and it should purge everything in `sites-enabled` apart from things it creates itself. It sounds like you are deploying a site called `default` and for some reason Puppet is unable to overwrite a symlink with a file.

I think it would be a good idea to manage site files in `sites-available` and have the module create symlinks. I'll put it on my dev list but I haven't got time to do it right now.

**Comment by thtomate** [comment]
My Puppet does not care about content if it is a symlink (there is a warning which has been ignored)
My site is named default for historical reasons, but I will change it anyway next time to differ for example mac-based and 802.1X authentication

**Comment by paulseward** [comment]
If I've understood correctly, the sequence of events is:
* install freeradius
* use puppet to manage it, deploying a site called `default`
* upgrading freeradius via a newer debian package overwrites the config file that's in sites-enabled, replacing it with a symlink to sites-available/default
* puppet then doesn't purge that symlink (because the filename matches something it's been told to deploy) but doesn't replace it with your desired `default` site

I can see that happening, and I can see it being a problem (especially as a lot of documentation says to use the default site and modify it to suit your needs)

The workaround is to name your site something other than `default` (which will then correctly purge the symlink and won't conflict with the package)

I think on balance though, that I agree we "should" be behaving the documented way, with files in sites-available and symlinks in sites-enabled

It's probably not a huge amount of work to implement, but may be a breaking change for some installs who are used to the existing model, so probably should either be opt-in or part of the next major release?

**Comment by djjudas21** [comment]
I think it would be OK for this module to place files in `sites-available` and add symlinks in `sites-enabled`. It should probably also do this for `mods-available` and `mods-enabled`.

I'm tied up with other dev work at the moment so I don't have time to look at this right now, but I'll happily accept a PR to implement this. We'll need to be careful with testing to make sure it doesn't break existing installs, and that can inform the decision whether it's opt-in or opt-out to get the new symlink behaviour.

**Comment by djjudas21** [comment]
I've now tagged `3.3.0` as a release with a fix for this behaviour. @thtomate thanks for reporting and @paulseward thanks for your fix.
